# Generated by Django 4.1.5 on 2023-08-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee", old_name="department", new_name="dept",
        ),
    ]
